name: C++ Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      
    - name: Install Dependencies
      shell: msys2 {0}
      run: pacman --noconfirm -S mingw-w64-x86_64-gcc

