name: C++ Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      
    - name: Install dependencies
      run: |
        pacman --noconfirm -S mingw-w64-x86_64-gcc
        
    - name: Build
      run: |
        g++ -o main.exe main.cpp
