name: Neofetch

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Install Neofetch
      run: sudo apt-get install -y neofetch

    - name: Run Neofetch
      run: neofetch
      

